# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Anchore Container Scan
        # You may pin to the exact commit or the version.
        # uses: anchore/scan-action@70af480f417f5ac0d4e31d38e5b44feb3f75d7ba
        uses: anchore/scan-action@v3.1.0
        with:
          # The image to scan. This option is mutually exclusive with "path". 
          image: #docker.io/jrrdev/cve-2017-5638:latest
          # The path to scan. This option is mutually exclusive with "image".
          path: .
          # Set this to any value to enable verbose debug output
          debug: true
          # Set to false to avoid failing based on severity-cutoff. Default is to fail when severity-cutoff is reached (or surpassed)
          fail-build: true
          # Generate a SARIF report and set the `sarif` output parameter after successful action execution.  This report is compatible with GitHub Automated Code Scanning (ACS), as the artifact to upload for display as a Code Scanning Alert report.
          acs-report-enable: # optional, default is true
          # Optionally specify the minimum vulnerability severity to trigger an "error" level ACS result.  Valid choices are "negligible", "low", "medium", "high" and "critical".  Any vulnerability with a severity less than this value will lead to a "warning" result.  Default is "medium".
          severity-cutoff: high
